apiVersion: apps/v1
kind: Deployment
metadata:
  name: snake-game
  namespace: snake-game
spec:
  replicas: 1
  selector:
    matchLabels:
      app: snake-game
  template:
    metadata:
      labels:
        app: snake-game
    spec:
      containers:
        - name: snake-game
          image: aschil/snake:latest
          ports:
            - containerPort: 80
