apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: snake-game
  namespace: snake-game
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: snake.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: snake-game
                port:
                  number: 80
